const CartConstest = {
    CART_START : 'CART_START',
    ADD_TO_CART : 'ADD_TO_CART',
    GET_ALL_PRODUCTS : 'GET_ALL_PRODUCTS',
    DECREASE_QTY : 'DECREASE_QTY',
    INCREASE_QTY : 'INCREASE_QTY',
    DELETE_CART : 'DELETE_CART'
}

export default CartConstest;